[build]
  command = "echo 'Skipping build step - using pre-built files'"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16.18.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 