[build]
  publish = "dist"
  command = "echo 'Using pre-built files in dist/'"

[build.environment]
  NODE_VERSION = "18.12.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 